FROM alpine:3.1


RUN apk add --update python py-pip

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

RUN adduser -D appuser
RUN chown appuser:appuser -R /app

EXPOSE  8000
ENTRYPOINT ["python"]
CMD ["main.py", "-p 8000"]