---

- name: Install Docker.
  hosts: "{{ hosts }}"
  become: true

  tasks:
    - name: Check Docker installed.
      command: systemctl status docker
      register: docker_state
      ignore_errors: yes

    - name: Get Docker installer.
      get_url:
        url: https://get.docker.com/
        dest: /tmp/install_docker.sh
        mode: 0700
      when: docker_state.stderr.find('service could not be found') != -1

    - name: Install Docker
      shell: /tmp/install_docker.sh
      when: docker_state.stderr.find('service could not be found') != -1

    - name: Remove installer file.
      file:
        state: absent
        path: /tmp/install_docker.sh

    - name: Enable Docker service
      service:
        name: docker
        enabled: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        
- name: Init swarm manager
  hosts: manager
  become: True
  gather_facts: False

  tasks:
    - name: Swarm init
      command: docker swarm init --advertise-addr {{ inventory_hostname }}

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token

    - name: Show Worker Token
      debug: var=worker_token.stdout

- name: Join swarm cluster as worker
  hosts: workers
  become: True
  gather_facts: False
  vars:
    token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['manager'][0]]['inventory_hostname'] }}"

  tasks:
    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }} {{ master }}:2377
      register: worker

    - name: Show Results
      debug: var=worker.stdout

    - name: Show Errors
      debug: var=worker.stderr
  